name: stamps
description: This package averages times lol
version: 0.0.2

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  args: ^1.6.0

scripts:
  build:
    exe: dart2native ./bin/main.dart -o bin/stamps.exe
    aot: dart2native ./bin/main.dart -k aot -o bin/stamps.aot